### ISSUE TITLE
[Question] interrogator_rpc create_dist_binary.bat error

### ISSUE THREAD

**Issue by Darkenlord1** [starik222/BooruDatasetTagManager#103]
When i try to run the "create_dist_binary.bat" (after installing pyinstaller), it gives me this error:

```
(venv) C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc>create_dist_binary.bat

(venv) C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc>del /Q dist

(venv) C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc>rem pyinstaller --clean main.spec --noconfirm

(venv) C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc>pyinstaller main.spec --noconfirm
210 INFO: PyInstaller: 6.3.0
211 INFO: Python: 3.10.11
225 INFO: Platform: Windows-10-10.0.19045-SP0
Traceback (most recent call last):
  File "C:\Users\darkenlord1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\darkenlord1\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc\venv\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc\venv\lib\site-packages\PyInstaller\__main__.py", line 214, in _console_script_run
    run()
  File "C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc\venv\lib\site-packages\PyInstaller\__main__.py", line 198, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc\venv\lib\site-packages\PyInstaller\__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc\venv\lib\site-packages\PyInstaller\building\build_main.py", line 1071, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc\venv\lib\site-packages\PyInstaller\building\build_main.py", line 1011, in build
    exec(code, spec_namespace)
  File "main.spec", line 11, in <module>
    *copy_metadata('tensorflow'),
  File "C:\Users\darkenlord1\Desktop\BDTM\interrogator_rpc\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 957, in copy_metadata
    dist = importlib_metadata.distribution(package_name)
  File "C:\Users\darkenlord1\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\darkenlord1\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for tensorflow
```

Is there something wrong with code or i am doing something wrong?

Could not find any guide here on github to how to even launch this thing sadly.

**Comment by thiagojramos** [comment]
you need to have the following packages installed:

```
        *copy_metadata('tqdm'),
        *copy_metadata('tensorflow'),
        *copy_metadata('torch'),
        *copy_metadata('regex'),
        *copy_metadata('requests'),
        *copy_metadata('packaging'),
        *copy_metadata('pillow'),
        *copy_metadata('filelock'),
        *copy_metadata('onnxruntime_gpu'),
        *copy_metadata('numpy'),
        *copy_metadata('tokenizers'),
        *copy_metadata('importlib_metadata'),

        *collect_data_files('transformers', include_py_files=True, includes=['**/*.py']),
```
