### ISSUE TITLE
Error when file - save changes in linux with virtual machine of win10

### ISSUE THREAD

**Issue by BrahRah** [starik222/BooruDatasetTagManager#117]
Error log:
```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.InvalidAsynchronousStateException: The saved data for the image "Y:\Cloth\Cloth_Bound001_16x16.png" does not match what is available in the program!!
Please post the file "C:\Users\user\Desktop\image taggers\BooruDatasetTagManager\ErrorData.json" in the issue
https://github.com/starik222/BooruDatasetTagManager/issues/104
   at BooruDatasetTagManager.DatasetManager.SaveAll()
   at BooruDatasetTagManager.MainForm.saveAllChangesToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
BooruDatasetTagManager
    Assembly Version: 2.1.3.0
    Win32 Version: 2.1.3.0
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/BooruDatasetTagManager.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Collections.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Private.Uri.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.ComponentModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Accessibility.dll
----------------------------------------
BooruDatasetTagManager.resources
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/en-US/BooruDatasetTagManager.resources.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Numerics.Vectors.dll
----------------------------------------
TabControl
    Assembly Version: 2.1.2.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/TabControl.dll
----------------------------------------
PagedControl
    Assembly Version: 2.2.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/PagedControl.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/mscorlib.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Threading.ThreadPool.dll
----------------------------------------
Grpc.Net.Client
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Grpc.Net.Client.dll
----------------------------------------
Grpc.Core.Api
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Grpc.Core.Api.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/netstandard.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
Grpc.Net.Common
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/Grpc.Net.Common.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.IO.Compression.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Runtime.Loader.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Core.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Resources.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Diagnostics.Process.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Net.NameResolution.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Collections.Immutable.dll
----------------------------------------
System.Linq.Parallel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Linq.Parallel.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/user/Desktop/image%20taggers/BooruDatasetTagManager/System.Text.RegularExpressions.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by starik222** [comment]
If you are using the latest version of the program, please attach the file "C:\Users\user\Desktop\image taggers\BooruDatasetTagManager\ErrorData.json"
