### ISSUE TITLE
Error installing Interrogator requirements

### ISSUE THREAD

**Issue by Latentnaut** [starik222/BooruDatasetTagManager#120]
Hi,

I run `interrogator_rpc>pip install -r requirements.txt` and found this issue. Any help please?

```
C:\AI\BDTM_V2.1.3_NetCore60_AllInclude\interrogator_rpc>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting git+https://github.com/huggingface/transformers (from -r requirements.txt (line 16))
  Cloning https://github.com/huggingface/transformers to c:\users\info\appdata\local\temp\pip-req-build-l7n_eri1
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers 'C:\Users\info\AppData\Local\Temp\pip-req-build-l7n_eri1'
  Resolved https://github.com/huggingface/transformers to commit 1681a6d452b60ff3652a96f03541dfa491124192
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting grpcio (from -r requirements.txt (line 2))
  Downloading grpcio-1.62.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Collecting grpcio-tools (from -r requirements.txt (line 3))
  Downloading grpcio_tools-1.62.0-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
Collecting onnx (from -r requirements.txt (line 4))
  Downloading onnx-1.15.0.tar.gz (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 72.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\info\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\info\AppData\Local\Temp\pip-build-env-lt9b3_9f\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\info\AppData\Local\Temp\pip-build-env-lt9b3_9f\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\info\AppData\Local\Temp\pip-build-env-lt9b3_9f\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 61, in <module>
      AssertionError: Could not find cmake in PATH
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\AI\BDTM_V2.1.3_NetCore60_AllInclude\interrogator_rpc>python main.py
Traceback (most recent call last):
  File "C:\AI\BDTM_V2.1.3_NetCore60_AllInclude\interrogator_rpc\main.py", line 25, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'
```

**Comment by Jelosus2** [comment]
Did you try to install grpc?

**Comment by Jelosus2** [comment]
nvm, it's because cmake is not on the PATH
