### ISSUE TITLE
use of underscore in tag cause exception error at line 68 of DatasetManager.cs

### ISSUE THREAD

**Issue by bondo01** [starik222/BooruDatasetTagManager#128]
I want to cover the use of underscore as a word separator in my tags. 
 example: body suit, body_suit, gray hair, grayhair, gray_hair,

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.InvalidAsynchronousStateException: The saved data for the image "E:\AI_Work\AI_training\Images_109.jpg" does not match what is available in the program!!
Please post the file "E:\BooruDatasetTagManager\BooruDatasetTagManager\ErrorData.json" in the issue
https://github.com/starik222/BooruDatasetTagManager/issues/104
   at BooruDatasetTagManager.DatasetManager.SaveAll()
   at BooruDatasetTagManager.MainForm.saveAllChangesToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by starik222** [comment]
Fixed in [2.1.5](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.1.5)
