### ISSUE TITLE
Viewer often causes exceptions and is unable to open preview

### ISSUE THREAD

**Issue by madrooky** [starik222/BooruDatasetTagManager#73]
When going through the list the viewer very often is unable to open a preview because "the file is used by another process". But that is not the case, all editors have been closed, only VSC, Firefox and Directory Opus (file manager) is open in the background and not even on the tab where the files are located. And even if it were, Directory Opus is read only once files and previews are loaded other wise i would have the same problems when editing files with Photoshop or else.
And this behavior is not even consistent, if i click through the list many open without problem, and sometimes ones that have caused the exception at one moment can be opened with the next attempt.

Makes it quite annoying using this amazing tool.

System.IO.IOException: The process cannot access the file 'G:\filepath\00005.png' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at BooruDatasetTagManager.Extensions.GetImageFromFile(String imagePath) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Extensions.cs:line 101
   at BooruDatasetTagManager.Form_preview.Show(String img) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form_preview.cs:line 32
   at BooruDatasetTagManager.Form1.ShowPreview(String img) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 144
   at BooruDatasetTagManager.Form1.LoadSelectedImageToGrid() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 0
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by starik222** [comment]
Check in version [2.0.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.0)

**Comment by madrooky** [comment]
> Check in version [2.0.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.0)

Awesome. Only checked quickly for the crashes, works now. Thank you very much!
