### ISSUE TITLE
[BUG] Crash when displaying tag count

### ISSUE THREAD

**Issue by Osmodin** [starik222/BooruDatasetTagManager#85]
There is currently a hard crash when trying to show tag count in all tags at this line...

if (item.Value.Tags[j].Tag == gridViewAllTags["Tag", i].Value.ToString())

System.ArgumentException
  HResult=0x80070057
  Message=Column named Tag cannot be found. (Parameter 'columnName')
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.DataGridViewCellCollection.get_Item(String columnName)
   at System.Windows.Forms.DataGridView.get_Item(String columnName, Int32 rowIndex)
   at BooruDatasetTagManager.MainForm.UpdateTagCount() in C:\Users\DTWor\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 1694
   at BooruDatasetTagManager.MainForm.MenuShowTagCount_Click(Object sender, EventArgs e) in C:\Users\DTWor\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 1673
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at BooruDatasetTagManager.Program.Main() in C:\Users\DTWor\BooruDatasetTagManager\BooruDatasetTagManager\Program.cs:line 85

**Comment by starik222** [comment]
Fixed in [2.0.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.1)
